apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: appropriate/curl
            command:
            - /bin/sh
            - -c
            - date; curl 192.168.49.2/ ; curl 192.168.49.2/dogs/ ; curl 192.168.49.2/cats/
            args: ["/bin/sh", "-c", ""]
            volumeMounts:
            - name: result
              mountPath: /result
          restartPolicy: OnFailure
          volumes:
          - name: result
            emptyDir: {}
