apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  serviceName: my-service
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: ng_wd
        imagePullPolicy: Never
        volumeMounts:
        - name: webdav
          mountPath: /var/www/webdav
  volumeClaimTemplates:
  - metadata:
      name: webdav
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
