apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-review-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats-dogs-review-app
  template:
    metadata:
      labels:
        app: cats-dogs-review-app
    spec:
      containers:
      - name: nginx
        image: cats-dogs-review-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx
      volumes:
      - name: config
        configMap:
          name: loadbalancer-config
