apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-review-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats-dogs-review-app
  template:
    metadata:
      labels:
        app: cats-dogs-review-app
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx
        - name: config
          mountPath: /usr/share/nginx/html
        resources:
            limits:
                cpu: "1"
                memory: "512Mi"
            requests:
                cpu: "0.5"
                memory: "256Mi"
        readinessProbe:
            httpGet:
                path: /
                port: 80
            initialDelaySeconds: 20  
            periodSeconds: 5
        livenessProbe:
            httpGet:
                path: /
                port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
      - name: config
        configMap:
          name: loadbalancer-config
      - name: static
        configMap:
          name: html-config
