apiVersion: apps/v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: animal-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  serviceName: my-service
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: garlik6/kuber
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: webdav
          mountPath: /var/www/webdav
  volumeClaimTemplates:
  - metadata:
      name: webdav
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mbi
